### PR TITLE
Added methods

### PR DESCRIPTION
**Pull request by pestanko**
* Work still in progress
* We are still developing tests and adding methods
* We are developing on Ruby 2.4.0 (don't sure which to support)
* We decided to split methods to separate managers, because one client.rb became too large.

------
CAN MERGE (Can review and all the comments are appreciated)

### CODE REVIEW

**Comment by mikz** [comment]
How would you like to proceed? Wait until you are done with it and then do the review ?

**Comment by pestanko** [comment]
I don't know, right now, we are implementing tests in our spare time. (So it takes some time)
Some tests are not passing
But you can check whether you like the structure we are using now.

You should completely review when we are done.

We have heard that you have some request from sales for new functionality, so you don't have to implement it again but use our implementation. I hope withing 2 week we will be done with tests

**Comment by mikz** [comment]
I think in general the split makes sense. There will be some cleanup required but no worries, that can be done later. The most important thing is that it works for you now.

Ping me here if there is anything you need help with.

**Comment by pestanko** [comment]
Hi you can review, we are done.

Yes there are some tests that are not passing. (Http client and something with reject account).

**Comment by andrewdavidmackenzie** [comment]
Pretty massive PR, so will take some time to review for sure.

Any chance of getting tests to pass, as we can't merge it if not....

**Pull request closed without merging**
